name: Prod apply
run-name: ${{ github.ref_name }}-${{ github.actor }}

on:
  workflow_dispatch:

jobs:
  terraform:
    uses: ./.github/workflows/terraform-apply.yaml
    with:
      environment: prod
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
