name: Infra CI
run-name: ${{ github.ref_name }}-${{ github.actor }}

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  terraform:
    uses: ./.github/workflows/terraform-plan-apply.yaml
    with:
      working-directory: .
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
